In [18]:
import pandas as pd
import numpy as np

#load in the data
data = np.array(pd.read_csv('initial_final.csv', header=None).values)[2:,1:]

Create Data Generator for the Net:

In [21]:
print(data[:,3:])

[[1.06627188 0.74543662]
 [1.06699165 0.74516139]
 [1.06758003 0.74493504]
 ...
 [1.12162046 0.15303183]
 [1.12168027 0.15248659]
 [1.12171143 0.15220721]]


In [51]:
# split the data into train/test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[:,1:3], data[:,3:], test_size=0.33, random_state=42)

In [52]:
print(X_train)

[[ 0.67676768  0.26060606]
 [ 0.01010101 -0.27272727]
 [ 0.85858586 -0.18787879]
 ...
 [ 0.07070707  0.49090909]
 [-0.83838384  0.12727273]
 [ 0.45454545  0.24848485]]


In [54]:
from keras.models import Sequential
from keras import layers
from keras.optimizers import RMSprop

model = Sequential()
model.add(layers.GRU(2))
#model.add(layers.Dense(2))

model.compile(optimizer=RMSprop(), loss='mae')
history = model.fit(X_train, y_train)

ValueError: in user code:

    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:805 train_function  *
        return step_function(self, iterator)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:788 run_step  **
        outputs = model.train_step(data)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:754 train_step
        y_pred = self(x, training=True)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:219 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_18 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 2)


In [46]:
import tensorflow as tf
model = Sequential(
    [
        layers.GRU(3, return_sequences=True, return_state=True),
        #layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(2, name="layer3"),
    ]
)
# Call model on a test input

model.compile(optimizer=RMSprop(), loss='mae')
history = model.fit(X_train, y_train)

ValueError: in user code:

    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:805 train_function  *
        return step_function(self, iterator)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:788 run_step  **
        outputs = model.train_step(data)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\training.py:754 train_step
        y_pred = self(x, training=True)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    D:\Anaconda\envs\Master_Thesis\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:219 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_16 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 3)


In [43]:
model.predict(X_test)

array([[-0.15009432,  0.2010762 ],
       [-0.15009432,  0.2010762 ],
       [-0.15009432,  0.2010762 ],
       ...,
       [-0.15009432,  0.2010762 ],
       [-0.15009432,  0.2010762 ],
       [-0.15009432,  0.2010762 ]], dtype=float32)